name: CI + Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t flask-devops-app .

      - name: Run tests
        run: docker run flask-devops-app pytest tests/

      - name: Install Railway CLI
        run: |
          curl -sL https://railway.app/install.sh | sh
          echo "$RAILWAY_API_KEY" > ~/.railway/token

      - name: Deploy to Railway
        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}
        run: railway up --detach
