name: CI + Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t flask-devops-app .

      - name: Run tests inside Docker container
        run: docker run flask-devops-app pytest tests/

      - name: Set up Node.js for Railway CLI
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Deploy to Railway
        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}
        run: railway up --detach
