name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t flask-devops-app .

      - name: Run tests inside container
        run: |
          docker run flask-devops-app pytest tests/
env:
  RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}
